name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: Welcome message
              run: |
                echo "My first github actions job"
                ls -ltr
                cat README.md

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "MOney money money" >> dragon.txt

            # - name: list files
            #   run: ls

            # - name: Read file
            #   run: cat README.md
            